name: "Update data automatically"

on:
  # 定时任务：每天 UTC 0点执行一次 (即北京时间早上8点)
  schedule:
    - cron: "*/5 * * * *"
  # 也允许手动触发
  workflow_dispatch:

permissions:
  contents: write  # 允许工作流对仓库contents写权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 拉取代码
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Step 2: 设置 Python（若你用Python）
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Step 3: 安装依赖（如 requests, bs4, etc.）
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      # Step 4: 执行你的脚本，更新 data.csv
      - name: Run the data-update script
        run: python scrape.py

      # Step 5: 提交并推送最新 data.csv
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data on $(date)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
